config/routes.rb
Colchonet::Application.routes.draw do
  resources :rooms
  resources :users
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]

  resources :rooms do
    resources :reviews, only: [:create, :update], module: :rooms
  end

  LOCALES = /en|pt\-BR/
  def index
    resources :users
  end
# Rails.application.routes.draw do
  scope "(:locale)", locale: LOCALES do
    resources :rooms
    resources :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/:locale' => 'home#index', locale: LOCALES
  root 'home#index'
end

app/models/room.rb
class Room < ApplicationRecord
  extend FriendlyId

  friendly_id :title, use: [:slugged, :history]

  validates_presence_of :title
  validates_presence_of :slug

  friendly_id :title, use: [:slugged, :history]

  has_many :reviews, dependent: :destroy
  has_many :reviewed_rooms, through: :reviews, source: :room
  belongs_to :user
  def complete_name
    "#{title}, #{location}, #{description}"
  end

  def self.search(query)
    if query.present?
      where(['location ILIKE :query OR title ILIKE :query OR description ILIKE :query', query: "%#{query}%"])
    else
      unscoped
    end
  end
end

app/controllers/rooms/reviews_controllers.rb
class Rooms::ReviewsControllers < ApplicationController
  before_action :require_authentication

  def create
    review = room.reviews.find_or_initialize_by(user_id: current_user.id)
    review.update!(review_params)
    head :ok
  end

  def update
    create
  end

  private

  def room
    @room ||= Room.find(params[:room_id])
  end

  def review_params
    params.require(:review).permit(:points)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  PER_PAGE = 10
  before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @search_query = params[:q]

    rooms = Room.search(@search_query).page(params[:page]).per(PER_PAGE)
    order = rooms.order(created_at: :desc).map

    # @rooms = rooms.order do |room|
    #   RoomPresenter.new(room,self,false)
    # end
    @rooms = RoomCollectionPresenter.new(rooms, self)
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    room_model = Room.friendly.find(params[:id])
    @room = RoomPresenter.new(room_model, self)
  end

  # GET /rooms/new
  def new
    @room = current_user.rooms.build
  end

  # GET /rooms/1/edit
  def edit
    @room = current_user.rooms.friendly.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      redirect_to @room, notice: t('flash.notice.room_created')
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    @room = current_user.rooms.friendly.find(params[:id])

    if @room.update(room_params)
      redirect_to @room, notice: t('flash.notice.room_updated')
    else
      render action: 'edit'
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json

  def destroy
    @room = current_user.rooms.friendly.find(params[:id])
    @room.destroy

    redirect_to room_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def belongs_to_user(room)
    user_signed_in? && room.user == current_user
  end
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      Error
    </div>
  <% end %>

  <%= form_for @room do |r| %>

  <div class="field">
    <%= r.label :title %>
    <%= r.text_field :title %>
    <%= error_tag @room, :title %>
  </div>

  <div class="field">
    <%= r.label :location %>
    <%= r.text_field :location %>
    <%= error_tag @room, :location %>
  </div>

  <div class="field">
    <%= r.label :description %>
    <%= r.text_area :description %>
    <%= error_tag @room, :description %>
  </div>
  
  <div class="actions">
    <%= r.submit %>
  </div>
<% end %>
<% end %>

app/views/rooms/_review.html.erb
<section class="review">
  <% if room.show_form? %>
    <%= render partial: "review_form", locals: {room: room} %>
  <% else %>
    <% room.stars.times do %>
      <span class="start filled_star"></span>
    <% end %>

    <% (room.review_points.max - room.stars).times do %>
      <span class="star empty_star"></span>
    <% end %>

    <%= t'.stats', count: room.total_reviews %>
  <% end %>
</section>

app/views/rooms/_review_form.html.erb
<% if room.can.review? %>
  <%= form_for room.review_route, remote: true do |f| %>
    <% room.review_points.each do |point| %>
      <%= f.radio_button :points, point %>
      <%= f.label :points, value: point do %>
        <i class="icon-star"></i>
      <% end %>
    <% end %>

    <%= f.submit %>
  <% end %>
<% else %>
  <span class="login_required">
    <%= t(".login_to_review") %>
  </span>
<% end %>

app/views/rooms/_room.html.erb
<article class="room">
  <h2>
    <%= link_to highlight(room.title, @search_query), room.route %>
  </h2>
  <%= render partial: 'review', locals: {room: room} %>
  <span class="created">
    <%= t'.owner_html', owner: room.user.full_name, when: l(room.created_at, format: :short) %>
  </span>
  <p>
    <span class="location">
      <%= link_to highlight(room.location, @search_query), "https://google.com/maps/search/#{room.location}", target: :blank %>
    </span>
  </p>
  <div class="room-description">
    <p><%= highlight(room.description || '', @search_query) %></p>
  </div>
  <% if belongs_to_user(room) %>
    <ul>
      <li><%= link_to t('.edit'), edit_room_path(room.route) %></li>
      <li><%= link_to t('.destroy'), room_path(room.route), method: :delete, data: {confirm: t('dialogs.destroy')}%></li>
    </ul>
  <% end %>
</article>

app/views/rooms/_search.html.erb
<%= form_tag rooms_path, method: :get, class: 'search' do %>
  <%= text_field_tag :q, @search_query, placeholder: t('.search_for') %>
<% end %>

app/views/rooms/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', room: @room %>

<%= link_to t('links.show'), @room %> |
<%= link_to t('links.back'), rooms_path %>

app/views/rooms/index.html.erb
<%= render 'search' %>

<h1>
  <% if @search_query.present? %>
    <%= t '.search_results' %>
  <% else %>
    <%= t '.title' %>
  <% end %>
</h1>

<%= render @rooms %>

<%= paginate @rooms %>

app/views/rooms/new.html.erb
<h1><%= t 'rooms.new' %></h1>

<%= render 'form', room: @room %>

<%= link_to t('links.back'), rooms_path %>

app/views/rooms/show.html.erb
<p>
  <strong><%= t('.title') %></strong>
  <%= @room.title %>
</p>
<p>
  <strong><%= t('.location') %></strong>
  <%= @room.location %>
</p>
<p>
  <strong><%= t('.description') %></strong>
  <%= @room.description %>
</p>
<% if belongs_to_user(@room) %>
<%= link_to t('links.edit'), edit_room_path(@room) %>
<% end %>
<%= link_to t('links.back'), rooms_path %>