config/routes.rb
Colchonet::Application.routes.draw do
  resources :rooms
  resources :users
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]

  resources :rooms do
    resources :reviews, only: [:create, :update], module: :rooms
  end

  LOCALES = /en|pt\-BR/
  def index
    resources :users
  end
# Rails.application.routes.draw do
  scope "(:locale)", locale: LOCALES do
    resources :rooms
    resources :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/:locale' => 'home#index', locale: LOCALES
  root 'home#index'
end

app/views/layouts/_user_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.new_room'), new_room_path %></li>
    <li><%= link_to t('layout.rooms'), rooms_path %></li>
    <li><%= link_to t('layout.my_profile'), user_path(current_user) %></li>
    <li><%= link_to t('layout.signout'), user_sessions_path, method: :delete %></li>
  </ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.rooms'), rooms_path %></li>
    <li><%= link_to t('layout.signup'), new_user_path %></li>
    <li><%= link_to t('layout.signin'), new_user_sessions_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColchoNet</title>
    <link href='https://fonts.googleapis.com/css?family=Pacifico&display=swap' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <div id='header-wrap'>
        <h1><%=link_to 'colcho.net', root_path %>
        <% if user_signed_in? %>
          <%= render 'layouts/user_navbar' %>
        <% else %>
          <%= render 'layouts/visitor_navbar' %>
        <% end %>
      </div>
    </header>
    <div id='content'>
      <% if notice.present? %>
        <p id='notice'><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p id='alert'><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>